[General]
firstTime=false
windowGeometry=@Rect(0 0 1920 1025)
windowMaximized=false
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\a\x80\0\0\x3\xba\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0\x45\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[AppSettings]
appMode=0
defaultJpgQuality=97
firstTime.nomacs.3=false

[CustomPluginShortcuts]
Composite%20Image=Composite Image
Crop%20to%20Metadata=Crop to Metadata
Crop%20to%20Page=Crop to Page
Draw%20to%20Page=Draw to Page
Fake%20Miniatures=Fake Miniatures
Image%20Transform=Image Transform
Paint%20on%20Image=Paint on Image

[DisplaySettings]
animateWidgets=false
bgColorNoMacsRGBA=4280163886
bgColorWidgetRGBA=2281701376
fgColorNoMacsRGBA=4291679988
highlightColorRGBA=4278225151
iconColorRGBA=4291679988
stylePlugin=qt6ct-style
themeName312=System.css

[DkAppManager]
Apps\1\appName=&File Manager
Apps\1\appPath=OpenDir
Apps\1\objectName=OpenDir
Apps\2\appName=&Default Application
Apps\2\appPath=OpenFile
Apps\2\objectName=OpenFile
Apps\size=2

[DkDialog]
saveTabsDialog=false
saveTabsDialog-answer=65536

[GlobalSettings]
numThreads=4
showBgImage=false

[Page%20Extraction%20Plugin]
Method=0

[SynchronizeSettings]
checkForUpdates=false
disableUpdateInteraction=false

[zooming]
useLevels=false
zoomLevels="0.0001,0.001,0.01,0.05,0.1,0.125,0.166,0.25,0.333,0.5,0.66,1,1.5,2,3,4,5,6,7,8,12,16,32,64,128"
