{ lib, pkgs, username, ... }:
{
  imports = [
    ./hardware.nix
    ]
      ++ lib.filesystem.listFilesRecursive ../../modules;

  # Define users
  users = {
#    users.root = {
#      hashedPassword = "xxxxxx"; could be generated by mkpasswd
#    };
    users."${username}" = {
      extraGroups = [
        "libvirtd"
        "networkmanager"
        "wheel"
      ];
      homeMode = "755";
      ignoreShellProgramCheck = true;
      isNormalUser = true;
      shell = pkgs.nushell;
    };
  };
}
