{
  # Specific Use Cases
  ## Hardware related
  Bluetooth = false;
  ### See https://github.com/blueman-project/blueman

  GPU-AMD = false;
  ### See https://nixos.wiki/wiki/AMD_GPU

  GPU-Nvidia = false;
  ### See https://nixos.wiki/wiki/Nvidia

  GPU-Intel = false;
  ### See https://nixos.wiki/wiki/Intel_Graphics

  HotSpot-Use-Case = false;
  ### See https://nixos.wiki/wiki/Internet_Connection_Sharing

  ZFS-Networking-HostID = "";
  ### See https://search.nixos.org/options?channel=unstable&show=networking.hostId&from=0&size=30&sort=relevance&query=networking.hostId
  ### Could be generated by `head -c4 /dev/urandom | od -A none -t x4`

  ZFS-Use-Case = false;
  ### See https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/index.html

  ## Software related
  QEMU-VM-Use-Case = false;
  ### See https://github.com/qemu/qemu ; https://github.com/virt-manager/virt-manager

  Transparent-Proxy = false;
  ### See https://github.com/daeuniverse/daed

  # Options
  ## System related
  BootLoader = "systemd-boot";
  ### Possible options: grub ; grub-mirror ; refind ; systemd-boot # See https://nixos.wiki/wiki/Bootloader https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=mirroredBoots

  DNS-Method = "Plain";
  ### Possible options: DoT ; Plain ; # See https://unbound.docs.nlnetlabs.nl/en/latest/getting-started/configuration.html

  KernelPackages = "linuxPackages_zen";
  ### Recommend option: linuxPackages_cachyos # See https://search.nixos.org/options?show=boot.kernelPackages https://www.nyx.chaotic.cx/#using-sched-ext-schedulers

  KeyboardLayout = "us";
  ### See https://en.wikipedia.org/wiki/Keyboard_layout

  Locale = "en_US.UTF-8";
  ### See https://docs.moodle.org/405/en/Table_of_locales

  StateVersion = "25.11";
  ### See https://mynixos.com/nixpkgs/option/system.stateVersion

  TimeSync-Method = "Plain";
  ### Possible options: NTS ; Plain ; # See https://github.com/pendulum-project/ntpd-rs

  TimeZone = "Asia/Singapore";
  ### See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  ## Wayland related
  MonitorSettings = "monitor = , preferred, auto, auto";
  ### MonitorSettings For Hyprland See https://wiki.hyprland.org/Configuring/Monitors/

  OutputSettings = "output * scale 1";
  ### OutputSettings For sway See https://github.com/swaywm/sway/wiki#display-configuration

  ScaleLevel = "2";
  ### For Hyprland see https://wiki.hyprland.org/Configuring/XWayland/#hidpi-xwayland
  ### For sway see https://github.com/swaywm/sway/wiki#hidpi

  WM = "Hyprland";
  ### Possible options: Hyprland ; niri ; sway
}
